# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import planner_pb2 as planner__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in planner_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlannerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GeneratePlan = channel.unary_unary(
                '/terra.planner.v1.PlannerService/GeneratePlan',
                request_serializer=planner__pb2.GeneratePlanRequest.SerializeToString,
                response_deserializer=planner__pb2.GeneratePlanResponse.FromString,
                _registered_method=True)


class PlannerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GeneratePlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlannerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GeneratePlan': grpc.unary_unary_rpc_method_handler(
                    servicer.GeneratePlan,
                    request_deserializer=planner__pb2.GeneratePlanRequest.FromString,
                    response_serializer=planner__pb2.GeneratePlanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'terra.planner.v1.PlannerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('terra.planner.v1.PlannerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlannerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GeneratePlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/terra.planner.v1.PlannerService/GeneratePlan',
            planner__pb2.GeneratePlanRequest.SerializeToString,
            planner__pb2.GeneratePlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
