# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: planner.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'planner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rplanner.proto\x12\x10terra.planner.v1\"\xad\x01\n\x13GeneratePlanRequest\x12\x0c\n\x04goal\x18\x01 \x01(\t\x12\x13\n\x0bworkflow_id\x18\x02 \x01(\t\x12\x43\n\x07\x63ontext\x18\x03 \x03(\x0b\x32\x32.terra.planner.v1.GeneratePlanRequest.ContextEntry\x1a.\n\x0c\x43ontextEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"T\n\x14GeneratePlanResponse\x12)\n\x05steps\x18\x01 \x03(\x0b\x32\x1a.terra.planner.v1.PlanStep\x12\x11\n\treasoning\x18\x02 \x01(\t\"Y\n\x08PlanStep\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x16\n\x0e\x61gent_selector\x18\x03 \x01(\t\x12\x14\n\x0c\x64\x65pendencies\x18\x04 \x03(\t2o\n\x0ePlannerService\x12]\n\x0cGeneratePlan\x12%.terra.planner.v1.GeneratePlanRequest\x1a&.terra.planner.v1.GeneratePlanResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'planner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEPLANREQUEST_CONTEXTENTRY']._loaded_options = None
  _globals['_GENERATEPLANREQUEST_CONTEXTENTRY']._serialized_options = b'8\001'
  _globals['_GENERATEPLANREQUEST']._serialized_start=36
  _globals['_GENERATEPLANREQUEST']._serialized_end=209
  _globals['_GENERATEPLANREQUEST_CONTEXTENTRY']._serialized_start=163
  _globals['_GENERATEPLANREQUEST_CONTEXTENTRY']._serialized_end=209
  _globals['_GENERATEPLANRESPONSE']._serialized_start=211
  _globals['_GENERATEPLANRESPONSE']._serialized_end=295
  _globals['_PLANSTEP']._serialized_start=297
  _globals['_PLANSTEP']._serialized_end=386
  _globals['_PLANNERSERVICE']._serialized_start=388
  _globals['_PLANNERSERVICE']._serialized_end=499
# @@protoc_insertion_point(module_scope)
